### ISSUE TITLE
[BUG] CodeCov is failing

### ISSUE THREAD

**Issue by dblock** [opensearch-project/project-tools#87]
### What is the bug?

```
_____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _\`|/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                               Ruby-0.6.0
==> GitHub Actions detected
x> No token specified or token is empty
==> Gzipping contents
==> Uploading reports
    url:   https://codecov.io/
    query: token=secret&flags&package=ruby-0.6.0&service=github-actions&branch=dependabot%2Fbundler%2Frexml-3.2.8&slug=opensearch-project%2Fproject-tools&build=9119704873&commit=e97e32d569fc3b26117ea53b60bb787b59812462
->  Pinging Codecov
https://codecov.io/upload/v4?token=secret&flags&package=ruby-0.6.0&service=github-actions&branch=dependabot%2Fbundler%2Frexml-3.2.8&slug=opensearch-project%2Fproject-tools&build=9119704873&commit=e97e32d569fc3b26117ea53b60bb787b59812462
{'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 2145s.', code='throttled')}
/home/runner/work/project-tools/project-tools/vendor/bundle/ruby/2.7.0/gems/codecov-0.6.0/lib/codecov/uploader.rb:56:in `upload': Could not upload reports to Codecov (StandardError)
	from /home/runner/work/project-tools/project-tools/vendor/bundle/ruby/2.7.0/gems/codecov-0.6.0/lib/codecov.rb:15:in `format'
	from /home/runner/work/project-tools/project-tools/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov/result.rb:51:in `format!'
	from /home/runner/work/project-tools/project-tools/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov/configuration.rb:197:in `block in at_exit'
	from /home/runner/work/project-tools/project-tools/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov.rb:189:in `run_exit_tasks!'
	from /home/runner/work/project-tools/project-tools/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov.rb:179:in `at_exit_behavior'
	from /home/runner/work/project-tools/project-tools/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov/defaults.rb:30:in `block in <top (required)>'
/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/ruby -I/home/runner/work/project-tools/project-tools/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.2/lib:/home/runner/work/project-tools/project-tools/vendor/bundle/ruby/2.7.0/gems/rspec-support-3.12.1/lib /home/runner/work/project-tools/project-tools/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.2/exe/rspec spec/github/commit_spec.rb spec/github/commits_spec.rb spec/github/contributor_spec.rb spec/github/contributors_spec.rb spec/github/data_spec.rb spec/github/issue_spec.rb spec/github/issues_spec.rb spec/github/organization_spec.rb spec/github/progress_spec.rb spec/github/pull_request_spec.rb spec/github/pull_requests_spec.rb spec/github/rate_limited_spec.rb spec/github/repos_spec.rb spec/github/searchable_spec.rb spec/github/signers_spec.rb spec/github/user_spec.rb spec/github/users_spec.rb spec/project/commands/contributors_spec.rb spec/project/commands/issues_spec.rb spec/project/commands/maintainers_spec.rb spec/project/commands/members_spec.rb spec/project/commands/org_spec.rb spec/project/commands/pr_spec.rb spec/project/commands/repos_spec.rb spec/project/project_spec.rb failed
```

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)
